#!/bin/bash
echo -n "Enter Link: "
read link
page=`curl "$link" --silent -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36'`
links=(`echo "$page" | pup 'div.container-chapter-reader img' | cut -d'"' -f2`)
i=1
start=1
for src in "${links[@]}"
do
	# Download image in the background
	curl \
		--silent \
		--create-dirs \
		--header 'Referer: https://readmanganato.com/' \
		--output "$i.jpg" \
		"$src" &
	((i++))
done
stop=`expr $i - 1`